#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    lock_passwd: false
    plain_text_passwd: 'insecure' 
ssh_pwauth: true
disable_root: false   
packages:
  - nginx
write_files:
 - content: |
      <html>
       <body>
        <h1>My WebShop</h1>
         <ul>
         <li><a href="/order">Order</a></li>
         <li><a href="/customer">Customer</a></li>
         <li><a href="/catalog">Catalog</a></li>
         </ul>
       </body>
      </html>
   path: /var/www/html/index.html
   permissions: '0644' 
 - content: |
        ##
        # Reverse Proxy server configuration
        #
        server {
                listen 80 default_server;
                listen [::]:80 default_server;
                root /var/www/html;
                index index.html;
                server_name _;
        
                location / {
                        # First attempt to serve request as file, then
                        # as directory, then fall back to displaying a 404.
                        try_files $uri $uri/ =404;
                }
                location /order {
                        proxy_pass      http://order-01/;
                }
        
                location /customer {
                        proxy_pass      http://customer-01/;
                }
                location /catalog {
                        proxy_pass      http://catalog-01/;
                }
        }
   path: /etc/nginx/sites-available/default
   permissions: '0644'
runcmd:
  - sudo systemctl restart nginx 