#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    lock_passwd: false
    plain_text_passwd: 'insecure' 
# ohne Funktion    
network:
  version: 2
  ethernets:  
    id0:
      match:
        name: e*
      wakeonlan: true
      dhcp4: false
      dhcp6: false
      addresses:
        - 192.168.123.8/24
      gateway4: 192.168.123.1  
      nameservers:
        search: 
          - 208.67.222.222 
          - 208.67.220.22
ssh_pwauth: true
disable_root: false   
runcmd:
  - curl -sfL https://raw.githubusercontent.com/mc-b/gns3/master/scripts/maas-network.sh | bash -  
  - curl -sfL https://raw.githubusercontent.com/mc-b/lerncloud/main/services/nfsshare.sh | bash -  
  - curl -sfL https://raw.githubusercontent.com/mc-b/lerncloud/main/services/vpn.sh | bash -
  - sudo su - ubuntu -c "curl -sfL https://raw.githubusercontent.com/mc-b/lerncloud/master/scripts/maas.sh | bash -"

  