#cloud-config
network:
  version: 2
  config:
    - type: physical
      name: ens3
      subnets:
        - type: static
          address: 192.168.123.8/24
          gateway: 192.168.123.1
    - type: nameserver
      address:
        - 208.67.222.222 
        - 208.67.220.22
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    lock_passwd: false
    plain_text_passwd: 'insecure' 
ssh_pwauth: true
disable_root: false   
runcmd:
  - curl -sfL https://raw.githubusercontent.com/mc-b/lerncloud/main/services/nfsshare.sh | bash -  
  - curl -sfL https://raw.githubusercontent.com/mc-b/lerncloud/main/services/vpn.sh | bash -
  - sudo su - ubuntu -c "curl -sfL https://raw.githubusercontent.com/mc-b/lerncloud/master/scripts/maas.sh | bash -"

  